package com.husen.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.husen.entity.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NickName = new Property(1, String.class, "nickName", false, "NICK_NAME");
        public final static Property SignName = new Property(2, String.class, "signName", false, "SIGN_NAME");
        public final static Property Sex = new Property(3, String.class, "sex", false, "SEX");
        public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
        public final static Property MaxScore = new Property(5, int.class, "maxScore", false, "MAX_SCORE");
        public final static Property Score = new Property(6, int.class, "score", false, "SCORE");
        public final static Property ArrayStr = new Property(7, String.class, "arrayStr", false, "ARRAY_STR");
        public final static Property Uri = new Property(8, String.class, "uri", false, "URI");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NICK_NAME\" TEXT," + // 1: nickName
                "\"SIGN_NAME\" TEXT," + // 2: signName
                "\"SEX\" TEXT," + // 3: sex
                "\"PHONE\" TEXT," + // 4: phone
                "\"MAX_SCORE\" INTEGER NOT NULL ," + // 5: maxScore
                "\"SCORE\" INTEGER NOT NULL ," + // 6: score
                "\"ARRAY_STR\" TEXT," + // 7: arrayStr
                "\"URI\" TEXT);"); // 8: uri
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(2, nickName);
        }
 
        String signName = entity.getSignName();
        if (signName != null) {
            stmt.bindString(3, signName);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(4, sex);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
        stmt.bindLong(6, entity.getMaxScore());
        stmt.bindLong(7, entity.getScore());
 
        String arrayStr = entity.getArrayStr();
        if (arrayStr != null) {
            stmt.bindString(8, arrayStr);
        }
 
        String uri = entity.getUri();
        if (uri != null) {
            stmt.bindString(9, uri);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(2, nickName);
        }
 
        String signName = entity.getSignName();
        if (signName != null) {
            stmt.bindString(3, signName);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(4, sex);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
        stmt.bindLong(6, entity.getMaxScore());
        stmt.bindLong(7, entity.getScore());
 
        String arrayStr = entity.getArrayStr();
        if (arrayStr != null) {
            stmt.bindString(8, arrayStr);
        }
 
        String uri = entity.getUri();
        if (uri != null) {
            stmt.bindString(9, uri);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nickName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // signName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
            cursor.getInt(offset + 5), // maxScore
            cursor.getInt(offset + 6), // score
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // arrayStr
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // uri
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNickName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSignName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSex(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMaxScore(cursor.getInt(offset + 5));
        entity.setScore(cursor.getInt(offset + 6));
        entity.setArrayStr(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUri(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
